/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.artsybashev.bacgame;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {
        BullsAndCowsGame game = new BullsAndCowsGame(4,"../app/src/main/resources/log.txt");
        game.startGame();
    }
}
